### ISSUE TITLE
AOB on movl build?

### ISSUE THREAD

**Issue by APN-Pucky** [gentoo/java-ebuilder#12]
![2024-05-05_11-44-16_apn](https://github.com/gentoo/java-ebuilder/assets/4533248/92b2ebfb-4f8c-4b89-be5d-a75064ebe673)

**Comment by fordfrog** [comment]
i get a similar issue:
```
$ java-ebuilder --refresh-cache --portage-tree /var/db/pkg/
WARNING: Keywords are used only when generating ebuild.
Parsing portage tree @ /var/db/pkg ...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: Range [14, 13) out of bounds for length 13
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865)
	at java.base/java.lang.String.substring(String.java:2834)
	at java.base/java.lang.String.substring(String.java:2807)
	at org.gentoo.java.ebuilder.portage.PortageParser.parseEbuild(PortageParser.java:255)
	at org.gentoo.java.ebuilder.portage.PortageParser.parsePackage(PortageParser.java:422)
	at org.gentoo.java.ebuilder.portage.PortageParser.parseCategory(PortageParser.java:240)
	at org.gentoo.java.ebuilder.portage.PortageParser.parseCategories(PortageParser.java:225)
	at org.gentoo.java.ebuilder.portage.PortageParser.parseTree(PortageParser.java:145)
	at org.gentoo.java.ebuilder.Main.refreshCache(Main.java:380)
	at org.gentoo.java.ebuilder.Main.main(Main.java:48)
```
