### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by efferre79** [gentoo/java-ebuilder#9]
If java-ebuilder-0.2 is run without arguments, an exception is triggered:

$ java-ebuilder
Exception in thread "main" java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at org.gentoo.java.ebuilder.Main.printUsage(Main.java:262)
        at org.gentoo.java.ebuilder.Main.main(Main.java:37)

**Comment by fordfrog** [comment]
this has been fixed recently
